In [2]:
import pandas as pd

In [12]:
italy = pd.read_csv('../Data/fianl_data_for_neural_network_italy.csv', sep='\t')
spain = pd.read_csv('../Data/fianl_data_for_neural_network_spain.csv', sep='\t')
france = pd.read_csv('../Data/fianl_data_for_neural_network_france.csv', sep='\t')
germany = pd.read_csv('../Data/fianl_data_for_neural_network_germany.csv', sep='\t')
england = pd.read_csv('../Data/fianl_data_for_neural_network_england.csv', sep='\t')

PoczÄ…tek kolejki - poczÄ…tek kolejki\

**Italia**\
2022-2023 -> 2022-08-13	(1) - 2022-10-21 (11)\
2021-2022 -> 2021-08-21	(1) - 2021-10-30 (11)\
2020-2021 -> 2020-09-19 (1) - 2020-12-11 (11)\
2019-2020 -> 2019-08-24	(1) - 2019-11-02 (11)\
2018-2019 -> 2018-08-18 (1) - 2018-11-02 (11)\
2017-2018 -> 2017-08-19	(1) - 2017-10-28 (11)

**Spain**\
2022-2023 -> 2022-08-12	(1) - 2022-10-22 (11)\
2021-2022 -> 2021-08-13	(1) - 2021-10-26 (11)\
2020-2021 -> 2020-09-12	(1) - 2020-11-27 (11)\
2019-2020 -> 2019-08-16 (1) - 2019-10-29 (11)\
2018-2019 -> 2018-08-17	(1) - 2018-11-03 (11)\
2017-2018 -> 2017-08-18 (1) - 2017-11-03 (11)

**Germany**\
2022-2023 -> 2022-08-05	(1) - 2022-10-21 (11)\
2021-2022 -> 2021-08-13	(1) - 2021-11-05 (11)\
2020-2021 -> 2020-09-18	(1) - 2020-12-11 (11)\
2019-2020 -> 2019-08-16	(1) - 2019-11-08 (11)\
2018-2019 -> 2018-08-24 (1) - 2018-11-09 (11)\
2017-2018 -> 2017-08-18	(1) - 2017-11-03 (11)

**France**\
2022-2023 -> 2022-08-05	(1) - 2022-10-14 (11)\
2021-2022 -> 2021-08-06	(1) - 2021-10-22 (11)\
2020-2021 -> 2020-08-21 (1) - 2020-11-20 (11)\
2019-2020 -> 2019-08-09	(1) - 2019-10-25 (11)\
2018-2019 -> 2018-08-10 (1) - 2018-10-26 (11)\
2017-2018 -> 2017-08-04	(1) - 2017-10-27 (11)


**England**\
2022-2023 -> 2022-08-05	(1) - 2022-10-14 (11)\
2021-2022 -> 2021-08-13	(1) - 2021-11-05 (11)\
2020-2021 -> 2020-09-12 (1) - 2020-12-05 (11)\
2019-2020 -> 2019-08-09	(1) - 2019-11-02 (11)\
2018-2019 -> 2018-08-10 (1) - 2018-11-03 (11)\
2017-2018 -> 2017-08-11	(1) - 2017-11-04 (11)

In [13]:
# England
england = england.drop('Unnamed: 0', axis=1)

england['game_date'] = pd.to_datetime(germany['game_date'], errors='coerce')

england.drop(england[(germany['game_date'] >= '2022-08-05') & (england['game_date'] < '2022-10-14')].index, inplace = True)
england.drop(england[(germany['game_date'] >= '2021-08-13') & (england['game_date'] < '2021-11-05')].index, inplace = True)
england.drop(england[(germany['game_date'] >= '2020-09-12') & (england['game_date'] < '2020-12-05')].index, inplace = True)
england.drop(england[(germany['game_date'] >= '2019-08-09') & (england['game_date'] < '2019-11-02')].index, inplace = True)
england.drop(england[(germany['game_date'] >= '2018-08-10') & (england['game_date'] < '2018-11-03')].index, inplace = True)
england.drop(england[(germany['game_date'] >= '2017-08-11') & (england['game_date'] < '2017-11-04')].index, inplace = True)

/var/folders/_h/ljwht4gd7lb99rm1hm78h7_00000gn/T/ipykernel_16342/3094183970.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  england.drop(england[(germany['game_date'] >= '2022-08-05') & (england['game_date'] < '2022-10-14')].index, inplace = True)
/var/folders/_h/ljwht4gd7lb99rm1hm78h7_00000gn/T/ipykernel_16342/3094183970.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  england.drop(england[(germany['game_date'] >= '2021-08-13') & (england['game_date'] < '2021-11-05')].index, inplace = True)
/var/folders/_h/ljwht4gd7lb99rm1hm78h7_00000gn/T/ipykernel_16342/3094183970.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  england.drop(england[(germany['game_date'] >= '2020-09-12') & (england['game_date'] < '2020-12-05')].index, inplace = True)
/var/folders/_h/ljwht4gd7lb99rm1hm78h7_00000gn/T/ipykernel_16342/3094183970.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  england.drop(england[(germany['game_date'] >= '2019-08-09') & (england['game_date'] < '2019-11-02')].index, inplace = True)
/var/folders/_h/ljwht4gd7lb99rm1hm78h7_00000gn/T/ipykernel_16342/3094183970.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  england.drop(england[(germany['game_date'] >= '2018-08-10') & (england['game_date'] < '2018-11-03')].index, inplace = True)
/var/folders/_h/ljwht4gd7lb99rm1hm78h7_00000gn/T/ipykernel_16342/3094183970.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  england.drop(england[(germany['game_date'] >= '2017-08-11') & (england['game_date'] < '2017-11-04')].index, inplace = True)

In [14]:
# Germany
germany = germany.drop('Unnamed: 0', axis=1)

germany['game_date'] = pd.to_datetime(germany['game_date'], errors='coerce')

germany.drop(germany[(germany['game_date'] >= '2022-08-05') & (germany['game_date'] < '2022-10-21')].index, inplace = True)
germany.drop(germany[(germany['game_date'] >= '2021-08-13') & (germany['game_date'] < '2021-11-05')].index, inplace = True)
germany.drop(germany[(germany['game_date'] >= '2020-09-18') & (germany['game_date'] < '2020-12-11')].index, inplace = True)
germany.drop(germany[(germany['game_date'] >= '2019-08-16') & (germany['game_date'] < '2019-11-08')].index, inplace = True)
germany.drop(germany[(germany['game_date'] >= '2018-08-24') & (germany['game_date'] < '2018-11-09')].index, inplace = True)
germany.drop(germany[(germany['game_date'] >= '2017-08-18') & (germany['game_date'] < '2017-11-03')].index, inplace = True)

In [15]:
# France
france = france.drop('Unnamed: 0', axis=1)

france['game_date'] = pd.to_datetime(france['game_date'], errors='coerce')

france.drop(france[(france['game_date'] >= '2022-08-05') & (france['game_date'] < '2022-10-14')].index, inplace = True)
france.drop(france[(france['game_date'] >= '2021-08-06') & (france['game_date'] < '2021-10-22')].index, inplace = True)
france.drop(france[(france['game_date'] >= '2020-08-21') & (france['game_date'] < '2020-11-20')].index, inplace = True)
france.drop(france[(france['game_date'] >= '2019-08-09') & (france['game_date'] < '2019-10-25')].index, inplace = True)
france.drop(france[(france['game_date'] >= '2018-08-10') & (france['game_date'] < '2018-10-26')].index, inplace = True)
france.drop(france[(france['game_date'] >= '2017-08-04') & (france['game_date'] < '2017-10-27')].index, inplace = True)

In [16]:
# Spain
spain = spain.drop('Unnamed: 0', axis=1)

spain['game_date'] = pd.to_datetime(spain['game_date'], errors='coerce')

spain.drop(spain[(spain['game_date'] >= '2022-08-12') & (spain['game_date'] < '2022-10-22')].index, inplace = True)
spain.drop(spain[(spain['game_date'] >= '2021-08-13') & (spain['game_date'] < '2021-10-26')].index, inplace = True)
spain.drop(spain[(spain['game_date'] >= '2020-09-12') & (spain['game_date'] < '2020-11-27')].index, inplace = True)
spain.drop(spain[(spain['game_date'] >= '2019-08-16') & (spain['game_date'] < '2019-10-29')].index, inplace = True)
spain.drop(spain[(spain['game_date'] >= '2018-08-17') & (spain['game_date'] < '2018-11-03')].index, inplace = True)
spain.drop(spain[(spain['game_date'] >= '2017-08-18') & (spain['game_date'] < '2017-11-03')].index, inplace = True)

In [17]:
# Italia
italy = italy.drop('Unnamed: 0', axis=1)

italy['game_date'] = pd.to_datetime(italy['game_date'], errors='coerce')

italy.drop(italy[(italy['game_date'] >= '2022-08-13') & (italy['game_date'] < '2022-10-22')].index, inplace = True)
italy.drop(italy[(italy['game_date'] >= '2021-08-21') & (italy['game_date'] < '2021-10-30')].index, inplace = True)
italy.drop(italy[(italy['game_date'] >= '2020-09-19') & (italy['game_date'] < '2020-12-11')].index, inplace = True)
italy.drop(italy[(italy['game_date'] >= '2019-08-24') & (italy['game_date'] < '2019-11-02')].index, inplace = True)
italy.drop(italy[(italy['game_date'] >= '2018-08-18') & (italy['game_date'] < '2018-11-02')].index, inplace = True)
italy.drop(italy[(italy['game_date'] >= '2017-08-19') & (italy['game_date'] < '2017-10-28')].index, inplace = True)

In [23]:

dane = pd.concat([england, germany, france, spain, italy], ignore_index=True, sort=False)

In [24]:
dane

,home_team_last_5_search_team_summary_goals,home_team_last_5_search_team_summary_shots,home_team_last_5_search_team_summary_shots_on_target,home_team_last_5_search_team_summary_xg,home_team_last_5_search_team_summary_npxg,home_team_last_5_search_team_summary_xg_assist,home_team_last_5_search_team_summary_sca,home_team_last_5_search_team_summary_gca,home_team_last_5_search_team_passes_xg_assist,home_team_last_5_search_team_passes_passes_into_final_third,...,away_team_last_3_search_team_elo,away_team_last_3_opponent_team_elo,away_team_last_3_rival_difference_elo,away_team_last_3_result,result,game_date,home_team,home_team_elo,away_team,away_team_elo
0,1.0,11.8,3.6,1.00,1.00,0.72,19.6,1.4,0.72,26.8,...,1642.826090,1675.349772,-32.523682,1.000000,3.0,2022-10-14,West Ham,1768.621948,Fulham,1655.402832
1,1.2,11.4,5.2,1.04,0.86,0.74,19.8,2.0,0.74,21.6,...,1703.039714,1719.828451,-16.788737,1.000000,3.0,2022-10-15,Crystal Palace,1748.520630,Leeds,1708.192261
2,2.2,19.0,7.0,2.10,2.10,1.48,32.8,4.0,1.48,47.0,...,2041.754435,1909.427165,132.327271,1.666667,3.0,2022-10-15,Arsenal,1889.969116,Liverpool,1984.582153
3,1.0,10.8,3.8,1.24,1.24,1.00,19.2,2.0,1.00,25.0,...,1822.588989,1793.620565,28.968424,1.000000,0.0,2022-10-15,Everton,1711.964233,Man United,1809.977295
4,0.8,11.2,2.0,1.22,1.06,0.88,18.2,1.2,0.88,24.4,...,1727.575724,1701.520386,26.055339,2.333333,1.0,2022-10-15,Forest,1587.895874,Aston Villa,1723.276001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8701,1.8,14.0,5.6,1.10,1.10,0.80,24.8,2.8,0.80,38.4,...,1528.692505,1561.096354,-32.403849,2.000000,3.0,2018-05-20,Napoli,1856.183838,Crotone,1546.066772
8702,1.0,9.4,3.4,0.88,0.72,0.52,16.8,1.8,0.52,19.8,...,1632.804728,1589.065470,43.739258,2.000000,3.0,2018-05-20,SPAL,1544.446411,Sampdoria,1614.712280
8703,1.6,12.0,5.2,0.90,0.90,0.78,21.6,2.8,0.78,40.2,...,1673.859090,1716.829224,-42.970133,1.333333,3.0,2018-05-20,Milan,1709.776001,Fiorentina,1697.576904
8704,1.2,13.6,5.6,1.04,0.90,0.60,21.6,2.2,0.60,26.8,...,1830.514445,1865.725627,-35.211182,1.666667,1.0,2018-05-20,Sassuolo,1601.294678,Roma,1844.738159
8705,2.4,15.6,5.6,2.06,1.76,1.56,29.8,4.6,1.56,35.0,...,1748.221476,1705.449056,42.772420,0.666667,0.0,2018-05-20,Lazio,1765.380859,Inter,1744.869751

In [ ]:
dane.to_csv('../Data/fianl_data_for_neural_network_2.csv', sep='\t', encoding='utf-8')